- hosts: mongodb
  become: yes
  tasks:
  - set_fact:
       mongodb_main_grp: "{{group_names[0]}}"
  - debug:
      var: hostvars.group_names
  - set_fact:
      subgroups_unfiltered: "{{ subgroups_unfiltered|default([])|unique + hostvars[item].group_names }}"
    loop: "{{ groups[mongodb_main_grp] }}"
  - set_fact:
      subgroup: "{{ subgroups_unfiltered|unique|difference([mongodb_main_grp]) }}"
  - debug:
      var: subgroup
    run_once: true
  - debug:
      msg: "{{ansible_hostname}} in {{item}} == {{inventory_hostname in groups[item]}}"
    when: inventory_hostname in groups[item]
    loop:   "{{subgroup}}"
 

