all:
    hosts:
    # None
    children:
        mongodb:
            hosts:
                sl-002819.sol.labwi.sva.de:
                sl-002820.sol.labwi.sva.de:
                  arbiter: true
                sl-002821.sol.labwi.sva.de:
            vars:
                repl_set_name: rs0
                mongodb_admin_user: admin
                #                mongodb_admin_pwd: admin
                replicaset: true
                users:
                - name: user1
                  database: db1
                  roles:
                  - readWrite
                - name: user2
                  database: db1
                  roles:
                  - read
                - name: admin2
                  database: admin
                  roles:
                  - readWrite
                 
    vars:
        ansible_become_method: sudo
        # Custom Config
        net_compressors: zlib,snappy
        mongod_config_template: mongod-custom.conf.j2 
        # TLS
        mongodb_use_tls: true
        mongodb_certificate_key_file: /opt/mongo/mongod.pem
        mongodb_certificate_ca_file: /opt/mongo/ca.pem
        # Vault 
        use_vault: true
        vault_root_path: cubbyhole/mongodb/
