---
- hosts: replica_sets
  become: yes
  tasks:
  - name: Ensure replicaset has reached a converged state
    community.mongodb.mongodb_status:
      replica_set: "rs0"
      login_database: admin
      login_user: admin
      login_password: admin
      login_host: sl-002819.sol.labwi.sva.de 
      ssl: yes
      ssl_ca_certs: "{{ mongodb_certificate_ca_file }}"
      ssl_certfile: "{{ mongodb_certificate_cert_file }}"
      ssl_keyfile: "{{mongodb_certificate_key_file}}"

    register: rs
  - debug:
      var: rs

  - name: Initialzize RS
    block:
    - name: Install pymongo
      pip:
        name: pymongo==3.12.2
    - name: Initialise MongoDB Replicaset rs0
      community.mongodb.mongodb_replicaset:
        login_database: admin
        login_user: admin
        login_password: admin
        login_host: sl-002821.sol.labwi.sva.de 

        #login_host: localhost
        ssl: yes
        ssl_ca_certs: "{{ mongodb_certificate_ca_file }}"
        ssl_certfile: "{{ mongodb_certificate_cert_file }}"
        ssl_keyfile: "{{mongodb_certificate_key_file}}"
        replica_set: "rs0"
        debug: true
        members: '{{groups["rs0"]}}'
      register: repl

    - name: Ensure replicaset has reached a converged state
      community.mongodb.mongodb_status:
        replica_set: "rs0"
        poll: 10
        interval: 10
        #when: repl.changed == True

    - name: Import mongodb_auth role
      include_role:
        name: community.mongodb.mongodb_auth
    when: ansible_hostname == groups["rs0"][0].split(".")[0]
